name: main

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  test_ubuntu:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.9
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Test square.py
      if: always() || failure()
      run: | 
        python -m unittest square.py
    - name: Test rectangle.py
      if: always() || failure()
      run: | 
        python -m unittest rectangle.py
    - name: Test triangle.py
      if: always() || failure()
      run: | 
        python -m unittest triangle.py
    - name: Test circle.py
      if: always() || failure()
      run: | 
        python -m unittest circle.py

  test_windows:
  
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.9
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Test square.py
      if: always() || failure()
      run: | 
        python -m unittest square.py
    - name: Test rectangle.py
      if: always() || failure()
      run: | 
        python -m unittest rectangle.py
    - name: Test triangle.py
      if: always() || failure()
      run: | 
        python -m unittest triangle.py
    - name: Test circle.py
      if: always() || failure()
      run: | 
        python -m unittest circle.py
